### ISSUE TITLE
12 user stories

### ISSUE THREAD

**Issue by erikgovea** [saniyaw7/Project1SE#2]
Coming up with 12 user stories. Priorities: Low cost, High value. High cost, High value. Low cost, Low value. High cost, Low value.

**Comment by MitPete** [comment]
Public Endpoint Stories

As a user, I want to view exercises by day of the week so that I can easily plan my workouts for specific days.
API: daysofweek

As a user, I want to filter exercises by the equipment I have available so that I can find workouts suited to my home gym or specific equipment.
API: equipment

As a user, I want to search for exercises by name so that I can quickly find specific exercises that I am familiar with.
API: exercise, exercisealias

As a user, I want to browse exercises by category so that I can find workouts based on the type of exercise (e.g., strength, cardio).
API: exercisecategory

As a user, I want to leave and read comments on exercises so that I can share feedback and learn from others' experiences.
API: exercisecomment

As a user, I want to view images of exercises so that I can see how they should be performed.
API: exerciseimage

As a user, I want to see basic details of exercises (such as name, category, and targeted muscles) so that I can better understand each workout.
API: exercisebaseinfo

As a user, I want to search for exercises that target specific muscles so that I can create a workout plan for specific muscle groups.
API: muscle

As a user, I want to set and track repetitions and weights for each exercise so that I can log my progress over time.
API: setting-repetitionunit, setting-weightunit

As a user, I want to access variations of each exercise so that I can adjust my workouts according to my skill level or equipment availability.
API: variation

As a user, I want to select ingredients and view their nutritional info so that I can plan meals that complement my exercise routine.
API: ingredient, ingredientinfo

As a user, I want to convert ingredient measurements to different weight units so that I can easily adjust recipes based on the quantities I need.
API: ingredienttoweightunit, weightunit
